import type { SVGProps } from "react";
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconApi,
  IconAntennaBars1,
  IconAntennaBars2,
  IconAntennaBars3,
  IconAntennaBars5,
  IconArrowBackUp,
  IconArrowDown,
  IconBolt,
  IconBrain,
  IconBook2,
  IconBrowser,
  IconCamera,
  IconCheck,
  IconChevronDown,
  IconClock,
  IconDeviceDesktop,
  IconDiamond,
  IconEye,
  IconEyeOff,
  IconFileSearch,
  IconFlame,
  IconGauge,
  IconHeadphones,
  IconHeart,
  IconInfoCircle,
  IconKey,
  IconLanguage,
  IconListDetails,
  IconMessageCircle,
  IconMicrophone,
  IconMoodSmile,
  IconMinus,
  IconMoon,
  IconPhotoSearch,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconPencil,
  IconPlugConnected,
  IconRefresh,
  IconRewindBackward10,
  IconRobot,
  IconSearch,
  IconSettings,
  IconShieldCheck,
  IconTargetArrow,
  IconSun,
  IconTool,
  IconTools,
  IconTrash,
  IconX,
  IconVolume,
  IconWaveSine,
  IconWorldSearch,
  type Icon as TablerIcon,
} from "@tabler/icons-react";

const ICONS: Record<string, TablerIcon> = {
  capture: IconCamera,
  tools: IconTools,
  tool: IconTool,
  search: IconSearch,
  "world-search": IconWorldSearch,
  fetch: IconFileSearch,
  browser: IconBrowser,
  "photo-search": IconPhotoSearch,
  "shield-check": IconShieldCheck,
  audio: IconWaveSine,
  api: IconApi,
  plug: IconPlugConnected,
  speech: IconMicrophone,
  speaker: IconVolume,
  settings: IconSettings,
  sliders: IconAdjustmentsHorizontal,
  history: IconClock,
  memory: IconListDetails,
  clock: IconClock,
  timer: IconClock,
  gauge: IconGauge,
  key: IconKey,
  bot: IconRobot,
  replies: IconMessageCircle,
  model: IconBrain,
  mic: IconMicrophone,
  headphones: IconHeadphones,
  play: IconPlayerPlay,
  refresh: IconRefresh,
  trash: IconTrash,
  languages: IconLanguage,
  moon: IconMoon,
  monitor: IconDeviceDesktop,
  quote: IconInfoCircle,
  info: IconInfoCircle,
  "alert-circle": IconAlertCircle,
  close: IconPlayerStop,
  stop: IconPlayerStop,
  check: IconCheck,
  wave: IconWaveSine,
  brain: IconBrain,
  "brain-circuit": IconBrain,
  zap: IconBolt,
  flame: IconFlame,
  anchor: IconTargetArrow,
  target: IconTargetArrow,
  book: IconBook2,
  theater: IconDiamond,
  heart: IconHeart,
  smile: IconMoodSmile,
  undo: IconArrowBackUp,
  rewind: IconRewindBackward10,
  sun: IconSun,
  eye: IconEye,
  "eye-off": IconEyeOff,
  chevron: IconChevronDown,
  plus: IconPlus,
  edit: IconPencil,
  minus: IconMinus,
  x: IconX,
  "level-1": IconAntennaBars1,
  "level-2": IconAntennaBars2,
  "level-3": IconAntennaBars3,
  "level-4": IconAntennaBars5,
  down: IconArrowDown,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.8,
  ...props
}: SVGProps<SVGSVGElement> & { name: string }) {
  const Component = ICONS[name] ?? ICONS.settings;

  return (
    <Component
      className={className}
      strokeWidth={Number(strokeWidth) || 1.8}
      aria-hidden="true"
      {...props}
    />
  );
}
